#!/bin/bash

#This script should be edited to execute any merge scripts needed to
#merge plugins and theme files before starting ConnextCMS/KeystoneJS.

#Execute merge scripts. Put in path to each merge script you want to run here.
~/theme/rtb4/merge-plugin

#Launch KeystoneJS and ConnextCMS
cd ~/myCMS
node keystone.js
